# Generated by Django 3.2.20 on 2024-05-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendlink',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False, verbose_name='友链ID')),
                ('link_url', models.URLField(verbose_name='友链地址')),
                ('link_desc', models.CharField(max_length=100, verbose_name='友链描述')),
                ('link_name', models.CharField(max_length=20, verbose_name='友链名称')),
                ('link_avatar', models.ImageField(default='default.jpg', upload_to='uploads/', verbose_name='友链头像')),
            ],
            options={
                'verbose_name': '友链',
                'verbose_name_plural': '所有友链',
                'db_table': 'friendlinks',
            },
        ),
    ]
