# Generated by Django 3.2.20 on 2025-03-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_auto_push', models.BooleanField(default=False, verbose_name='启用自动推送')),
                ('repo_url', models.URLField(blank=True, help_text='例如：https://github.com/username/username.github.io.git', verbose_name='GitHub Pages仓库URL')),
                ('repo_branch', models.CharField(default='master', help_text='通常是master或main', max_length=50, verbose_name='推送分支')),
            ],
            options={
                'verbose_name': 'Git配置',
                'verbose_name_plural': 'Git配置',
            },
        ),
    ]
