# Generated by Django 3.2.20 on 2024-05-09 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_friendlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='无题', max_length=50, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(default='未分类', max_length=20, verbose_name='类别名称'),
        ),
    ]
