# Generated by Django 3.2.20 on 2025-03-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_gitconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitconfig',
            name='github_token',
            field=models.CharField(blank=True, help_text='从GitHub设置页面生成的个人访问令牌', max_length=100, verbose_name='GitHub Personal Access Token'),
        ),
        migrations.AlterField(
            model_name='gitconfig',
            name='repo_url',
            field=models.URLField(blank=True, help_text='使用HTTPS格式，例如：https://github.com/username/username.github.io.git', verbose_name='GitHub Pages仓库URL'),
        ),
    ]
