# Generated by Django 3.2.20 on 2025-03-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250315_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='我的博客', max_length=100, verbose_name='网站名称')),
                ('favicon', models.ImageField(blank=True, help_text='建议上传 .ico 格式的图标文件，尺寸为 32x32 或 16x16 像素', null=True, upload_to='favicon/', verbose_name='网站图标')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
        migrations.AlterField(
            model_name='gitconfig',
            name='github_token',
            field=models.CharField(blank=True, help_text='从GitHub设置页面生成的个人访问令牌（需要repo权限）', max_length=100, verbose_name='GitHub Personal Access Token'),
        ),
    ]
