# Generated by Django 3.2.20 on 2025-03-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20250318_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlink',
            name='link_email',
            field=models.EmailField(blank=True, help_text='用于生成默认头像，不会公开显示', max_length=254, null=True, verbose_name='友链邮箱'),
        ),
        migrations.AlterField(
            model_name='friendlink',
            name='link_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='友链头像'),
        ),
    ]
